-- Migration: Drop stored procedures for all main tables
-- Date: 2024-07-26

-- USERS
DROP FUNCTION IF EXISTS sp_insert_user(TEXT, TEXT, TEXT, TIMESTAMP);
DROP FUNCTION IF EXISTS sp_update_user_details(BIGINT, TEXT);
DROP FUNCTION IF EXISTS sp_update_user_password(BIGINT, TEXT);
DROP FUNCTION IF EXISTS sp_update_user_session(BIGINT, TEXT, TIMESTAMP);
DROP FUNCTION IF EXISTS sp_update_user_is_admin(BIGINT, BOOLEAN);
DROP FUNCTION IF EXISTS sp_delete_user(BIGINT);
DROP FUNCTION IF EXISTS sp_get_user_by_email(TEXT);
DROP FUNCTION IF EXISTS sp_get_user_password(BIGINT);
DROP FUNCTION IF EXISTS sp_get_user_by_id(BIGINT);
DROP FUNCTION IF EXISTS sp_get_users_not_deleted();
DROP FUNCTION IF EXISTS sp_update_user_is_enabled(_id BIGINT, _is_enabled BOOLEAN);
DROP FUNCTION IF EXISTS sp_logout_user(BIGINT);
-- PROJECTS
DROP FUNCTION IF EXISTS sp_insert_project(TEXT, TEXT, BIGINT, DATE, DATE, BIGINT, TIMESTAMP, BIGINT, TIMESTAMP, BOOLEAN, BOOLEAN);
DROP FUNCTION IF EXISTS sp_update_project(BIGINT, TEXT, TEXT, BIGINT, DATE, DATE, BIGINT, TIMESTAMP);
DROP FUNCTION IF EXISTS sp_delete_project(BIGINT, BIGINT, TIMESTAMP);
DROP FUNCTION IF EXISTS sp_get_projects_by_user(BIGINT);
DROP FUNCTION IF EXISTS sp_get_project(BIGINT);
DROP FUNCTION IF EXISTS sp_get_project_count(BIGINT);
-- TASKS (TASKS)
DROP FUNCTION IF EXISTS sp_insert_task(TEXT, TEXT, INTEGER, BIGINT, DATE, BIGINT, TIMESTAMP, BIGINT, TIMESTAMP, BIGINT);
DROP FUNCTION IF EXISTS sp_update_task(BIGINT, TEXT, TEXT, BIGINT, DATE, BIGINT);
DROP FUNCTION IF EXISTS sp_update_task_status(BIGINT, INTEGER, TIMESTAMP, BIGINT, TIMESTAMP);
DROP FUNCTION IF EXISTS sp_delete_task(BIGINT, BIGINT, TIMESTAMP);
DROP FUNCTION IF EXISTS sp_restore_task(BIGINT, BIGINT, TIMESTAMP);
DROP FUNCTION IF EXISTS sp_get_tasks_by_user(BIGINT);
DROP FUNCTION IF EXISTS sp_get_tasks_by_user_and_project(BIGINT, BIGINT);
DROP FUNCTION IF EXISTS sp_get_task(BIGINT);
DROP FUNCTION IF EXISTS sp_get_tasks_count(BIGINT);
DROP FUNCTION IF EXISTS sp_get_completed_project_tasks(BIGINT);
DROP FUNCTION IF EXISTS sp_get_total_project_tasks(BIGINT);
-- PROJECT_USERS
DROP FUNCTION IF EXISTS sp_insert_project_user(BIGINT, BIGINT, BIGINT);
DROP FUNCTION IF EXISTS sp_update_project_user(BIGINT, BIGINT, BIGINT);
DROP FUNCTION IF EXISTS sp_delete_project_user(BIGINT, BIGINT);
DROP FUNCTION IF EXISTS sp_get_all_project_users_for_project(BIGINT);
DROP FUNCTION IF EXISTS sp_get_all_project_users_for_user(BIGINT);
DROP FUNCTION IF EXISTS sp_get_project_user_roles(BIGINT, BIGINT);
-- ROLES
DROP FUNCTION IF EXISTS sp_get_all_roles();
