-- INITIAL DOWN  MIGRATION
-- Date: 2024-07-25
DROP TABLE IF NOT EXISTS project_users;
DROP TABLE IF NOT EXISTS tasks;
DROP TABLE IF NOT EXISTS projects;
DROP TABLE IF NOT EXISTS roles;
DROP TABLE IF NOT EXISTS users;
